---
matrix:
  fast_finish: true
  include:

    - name: "Python 2.7.17 on macOS xcode10.2"
      os: osx
      osx_image: xcode10.2  # travis-ci-macos10.14-xcode10.2-19-1573099784 (via amqp)
      language: shell # 'language: python' is an error on Travis CI macOS
      before_install:
        - pip install virtualenv
        - virtualenv -p $(which python2) ~venvpy2
        - source ~venvpy2/bin/activate
      install:
        - pip install codecov
        - pip install -r requirements.txt
      script:
        - python3 --version
        - python2 --version
        - python --version
        - pip list
        - whoami
        - pwd
        - coverage run tests.py
      after_success:
        - codecov
        - deactivate

    - name: "Python 3.7.5 on macOS xcode10.2"
      os: osx
      osx_image: xcode10.2  # travis-ci-macos10.14-xcode10.2-19-1573099784 (via amqp)
      language: shell # 'language: python' is an error on Travis CI macOS
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
      install:
        - pip3 install codecov
        - pip install -r requirements.txt
      script:
        - python3 --version
        - python2 --version
        - python --version
        - whoami
        - pwd
        - pip3 list
        - coverage run tests.py
      after_success:
        - codecov
        - deactivate

    - name: "Python 3.7.5 on macOS xcode9.4 "
      os: osx
      osx_image: xcode9.4  # travis-ci-macos10.13-xcode9.4.1-19-1576204381
      language: shell  # 'language: python' is an error on Travis CI macOS
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
      install:
        - pip3 install codecov
        - pip install -r requirements.txt
      script:
        - python3 --version
        - python2 --version
        - python --version
        - whoami
        - pwd
        - pip3 list
        - coverage run tests.py
      after_success:
        - codecov
        - deactivate
